/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as AvaliacaoIdRouteImport } from './routes/avaliacao.$id'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor.index'
import { Route as DashboardGrupoIdRouteImport } from './routes/dashboard.grupo.$id'
import { Route as SupervisorGrupoIdRouteImport } from './routes/supervisor.grupo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoIdRoute = AvaliacaoIdRouteImport.update({
  id: '/avaliacao/$id',
  path: '/avaliacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRoute,
} as any)
const DashboardGrupoIdRoute = DashboardGrupoIdRouteImport.update({
  id: '/grupo/$id',
  path: '/grupo/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const SupervisorGrupoIdRoute = SupervisorGrupoIdRouteImport.update({
  id: '/grupo/$id',
  path: '/grupo/$id',
  getParentRoute: () => SupervisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/avaliacao/$id': typeof AvaliacaoIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/dashboard/grupo/$id': typeof DashboardGrupoIdRoute
  '/supervisor/grupo/$id': typeof SupervisorGrupoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matrix': typeof MatrixRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/avaliacao/$id': typeof AvaliacaoIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
  '/dashboard/grupo/$id': typeof DashboardGrupoIdRoute
  '/supervisor/grupo/$id': typeof SupervisorGrupoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supervisor': typeof SupervisorRouteWithChildren
  '/avaliacao/$id': typeof AvaliacaoIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/dashboard/grupo/$id': typeof DashboardGrupoIdRoute
  '/supervisor/grupo/$id': typeof SupervisorGrupoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/matrix'
    | '/relatorio'
    | '/sitemap.xml'
    | '/supervisor'
    | '/avaliacao/$id'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/supervisor/'
    | '/dashboard/grupo/$id'
    | '/supervisor/grupo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matrix'
    | '/relatorio'
    | '/sitemap.xml'
    | '/avaliacao/$id'
    | '/dashboard/$id'
    | '/dashboard'
    | '/supervisor'
    | '/dashboard/grupo/$id'
    | '/supervisor/grupo/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/matrix'
    | '/relatorio'
    | '/sitemap.xml'
    | '/supervisor'
    | '/avaliacao/$id'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/supervisor/'
    | '/dashboard/grupo/$id'
    | '/supervisor/grupo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MatrixRoute: typeof MatrixRoute
  RelatorioRoute: typeof RelatorioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupervisorRoute: typeof SupervisorRouteWithChildren
  AvaliacaoIdRoute: typeof AvaliacaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao/$id': {
      id: '/avaliacao/$id'
      path: '/avaliacao/$id'
      fullPath: '/avaliacao/$id'
      preLoaderRoute: typeof AvaliacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/dashboard/grupo/$id': {
      id: '/dashboard/grupo/$id'
      path: '/grupo/$id'
      fullPath: '/dashboard/grupo/$id'
      preLoaderRoute: typeof DashboardGrupoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/supervisor/grupo/$id': {
      id: '/supervisor/grupo/$id'
      path: '/grupo/$id'
      fullPath: '/supervisor/grupo/$id'
      preLoaderRoute: typeof SupervisorGrupoIdRouteImport
      parentRoute: typeof SupervisorRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIdRoute: typeof DashboardIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGrupoIdRoute: typeof DashboardGrupoIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIdRoute: DashboardIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGrupoIdRoute: DashboardGrupoIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SupervisorRouteChildren {
  SupervisorIndexRoute: typeof SupervisorIndexRoute
  SupervisorGrupoIdRoute: typeof SupervisorGrupoIdRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorIndexRoute: SupervisorIndexRoute,
  SupervisorGrupoIdRoute: SupervisorGrupoIdRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MatrixRoute: MatrixRoute,
  RelatorioRoute: RelatorioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupervisorRoute: SupervisorRouteWithChildren,
  AvaliacaoIdRoute: AvaliacaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
